OUTPUT_SEPARATOR = ", "

MAX_LIST_LENGTH = 1000
MAX_STRING_LENGTH = 10_000

PAYLOAD_CREATED_MESSAGE = "Payload created"
PAYLOAD_EXISTS_MESSAGE = "Payload already exists"
PAYLOAD_NOT_FOUND_DETAIL = "Payload not found"
